<?php

namespace AO\AnalyzerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends EntityRepository
{

    /**
     * get bank account list in database
     * @return string
     */
    public function getAccountsListForm($container)
    {
        $aAccount = array();

        try {
            $oQB = $this->createQueryBuilder('a');
            $aoAccount = $oQB->getQuery()->getResult();
            foreach ($aoAccount as $oAccount)
            {
                $aAccount[$oAccount->getId()] = $oAccount->getCode() . ' - ' . $oAccount->getComment();
            }
        }
        catch (Doctrine\ORM\NoResultException $Exception) {
                
            $container->get('logger')->error($Exception->getMessage());
        }
        return $aAccount;
    }

}
