security:
    encoders:
        AO\AnalyzerBundle\Entity\User: 
            algorithm:          sha1
            encode_as_base64:   false
            iterations:         1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: AO\AnalyzerBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/
            anonymous: true
            form_login:
                login_path: login
                check_path: login_check
                username_parameter: "username"
                password_parameter: "password"
                provider: administrators
                intention: authentication
                success_handler: security.authentication.success_handler
            logout:
                path:   logout
                target: /

    access_control:
        - { path: ^/set_locale, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, roles: ROLE_ADMIN }
        
