parameters:
    # repertoire ou stocker les fichiers XLS
    dir_files: '/files/'
    per_page: 20
    # categories 
    categories:
        CC: 1
        LEVY: 2
        TRANSFER: 3
        CASH: 4
        CHE: 5
        RE_CHE: 6
        BANK_CHARGE: 7
        
    categorieLabel: 
        CC: 
            label: CREDIT CARD
            icon: fa fa-cc-visa
        LEVY:
            label: LEVY
            icon: fa fa-sign-out
        TRANSFER:
            label: TRANSFER
            icon : fa fa-sign-in
        CASH:
            label: CASH
            icon: fa fa-money
        CHE: 
            label: BANK CHECK
            icon: fa fa-pencil-square-o
        RE_CHE: 
            label: BANK RE CHECK
            icon: fa fa-pencil-square-o
        BANK_CHARGE: 
            label: BANK CHARGE
            icon: fa fa-bank