parameters:
    ao.statistics.class: AO\AnalyzerBundle\Service\Statistics

services: 

    ao.statistics:
        class: %ao.statistics.class%
        arguments: ['@service_container']
    
    acme_locale.locale_listener:
        class: AO\AnalyzerBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
